/* ----------------------------------------
Name: Ladbroker

Description: This is a LLM application, which passes any user's requirements 
to LLM to translate them into program codes, and then executes them.
For example: "What time is it now?" --> LLM -->
--> "use DateTime;my $time = DateTime->now();print "$time\n";"
--> execute above codes locally and output the result

Author: madbookhub@github

Created: Aug,18,2024
 
Recent: Oct,26,2024
---------------------------------------- */
#include <stdio.h>
#include <stdlib.h>

// for keyboard IO 
#include <unistd.h>
#include <termios.h>
#include <fcntl.h>

#include "common/common.h"
#include "terminal/terminal.h"
#include "broker/broker.h"
#include "executant/executant.h"

#define BUFSIZE 8192

#define PROMPT_FOREWORD "Advice:"
#define PROMPT_BREAK '`' // refer to the prompt file !

int IsKeyPressed()
{
int Current, Res;
char c;
struct termios Live, Temp;

tcgetattr(STDIN_FILENO, &Live); // get current Terminal IO setting
Temp = Live;
Temp.c_lflag &= ~(ICANON | ECHO); // disable canonical mode and echo
tcsetattr(STDIN_FILENO, TCSANOW, &Temp); // apply new setting temporarily

Current = fcntl(STDIN_FILENO, F_GETFL, 0);
fcntl(STDIN_FILENO, F_SETFL, Current | O_NONBLOCK); // set non-blocking mode

Res = read(STDIN_FILENO, &c, 1); // read the damn keyboard buffer finally

tcsetattr(STDIN_FILENO, TCSANOW, &Live); // restore Terminal IO setting
fcntl(STDIN_FILENO, F_SETFL, Current);

return (Res == 1);
}

char* Conclude(char* ReportofExecution)
{
char* Buf=NULL;

FILE* File = fopen(SCRIPT_NAME, "r");
if ( File == NULL ) return NULL;

// get size of script file which was generated by LLM
fseek(File, 0, SEEK_END);
long FileSize = ftell(File);
fseek(File, 0, SEEK_SET);

// and the size of response of LLM
int ReportSize = strlen(ReportofExecution);

// Now allocate memory to combine the content of script and response of LLM.
// Two more rooms for the Section-Break of prompt, and terminator character.
int TotalSize = strlen(PROMPT_FOREWORD) + FileSize + ReportSize + 2;
Buf = Alloc( TotalSize );
if (Buf != NULL)
	{
	// generate the content post to LLM
	char* p = Buf;
	SmoothText(PROMPT_FOREWORD, p), p+=strlen(PROMPT_FOREWORD);
	SmoothText(ReportofExecution, p), p+=ReportSize;
	*p = PROMPT_BREAK, ++p;
	fread(p, sizeof(char), FileSize, File);

	// escaped
	char* BufofEscaped = EnEscaped(Buf);
	if (BufofEscaped == NULL || BufofEscaped != Buf) Freealloc(Buf);
	Buf = BufofEscaped;
	}

fclose(File);

return Buf;
}

int OnSubmitfromTerminal(const int Terminal, const char* Submission)
{
int Result=-1;
char *Buffer=NULL, *Recycle=NULL;

if ( (Buffer = Alloc(BUFSIZE)) == NULL ) return Result;

while (1)
	{
	// Talk to LLM to get some codes which should be saved to local script.
	Result = Ask(Recycle!=NULL, BUFSIZE, (Recycle==NULL)?Submission:Recycle, Buffer);
	if (Result) break;

	// Try to execute the codes...quit if it works or malfunctioned. 
	if (Execute(Terminal, BUFSIZE, Buffer) != ERROR_CODE) break;

	// Try again if there are some problems with the codes.
	Freealloc(Recycle);
	Recycle = (char*)Conclude(Buffer);
	if ( Recycle == NULL ) break;

	// If there is keystrokes, it may be that user is impatient,quit.
	if (IsKeyPressed()) break;
	}

Freealloc(Recycle);
Freealloc(Buffer);
return Result;
}

void OnTerminalCloses(){ NomoreAsk(); }

int main(int argc, char* argv[])
{
InitProxy(argc, argv);
return OpenTerminal( &OnSubmitfromTerminal, &OnTerminalCloses );
}
